#!/bin/bash

echo"

 :::===  :::  === :::====  :::====  :::====  :::====  :::= === :::====  :::==== 
 :::     :::  === :::  === :::  === :::  === :::  === :::===== :::  === :::  ===
  =====  ===  === ===  === ===  === =======  ======== ======== ===  === ========
     === ===  === ===  === ===  === ===      ===  === === ==== ===  === ===  ===
 ======   ======  =======   ======  ===      ===  === ===  === =======  ===  ===
 
 "



echo "This script is simply designed to install the 
needed components to run the Mac Updater script.
You must have admin rights for installations 
in order to run this program."

echo "Items that will be installed are Git and Speedtest CLI 
"
echo "Ensure only authorized users are logged in on this machine"
w

echo "Checking current version of Git. If Git is not installed already, it will prompt you to install it."
git --version
echo "Download complete"

echo "
Preparing to install Speedtest CLI"
git clone https://github.com/sivel/speedtest-cli
echo "Download complete"

echo "All items are now ready. You can now run the Mac updater!"

